### ISSUE TITLE
Add a test case that demonstrates the uses of 2 communicating pods

### ISSUE THREAD

**Issue by rsearls** [Intersmash/intersmash#107]
Provide a test that demonstrates the creation and use of 2 communicating 
OpenShift pods.

The test case is a jaxws application that demonstrates the creation of
2 communicating OpenShift pods. One pod is a Security Token Service (STS). 
The other is the web service provider. The test itself is the web service 
requester. Modules sts and service build a bootable jar that is deployed to 
OpenShift.

**Comment by fabiobrz** [comment]
Closed as resolved via #108
