### ISSUE TITLE
Fix Regularly failing CI test

### ISSUE THREAD

**Issue by rsearls** [Intersmash/intersmash#167]
These 2 CI tests fail regularly on first run of a PR.
The PR does not have to touch any of the code related to
these test.
One must "retest" these tests only in order to pass.  
The cause needs to be identified and resolved.
    ci/prow/intersmash-e2e
    ci/prow/prod-intersmash-e2e-prod

**Expected behavior**
These tests should run and pass on 1st just like the other tests.

**Comment by fabiobrz** [comment]
Hi @rsearls - This issue can be closed as the OpenShift Prow based CI checks have been removed, see https://github.com/Intersmash/intersmash/discussions/186
