### ISSUE TITLE
Remove unused OS based differentiation from the CommandLineBasedKeystoreGenerator::getSplitCommandNameBasedOnOeratingSystem method

### ISSUE THREAD

**Issue by fabiobrz** [Intersmash/intersmash#198]
The [`CommandLineBasedKeystoreGenerator::getSplitCommandNameBasedOnOeratingSystem`](https://github.com/Intersmash/intersmash/blob/main/core/src/main/java/org/jboss/intersmash/util/CommandLineBasedKeystoreGenerator.java#L296) method is taking the `mac` value for the `os.name` system property into account, which doesn't make sense, since Intersmash only supports Linux execution.

The method should be removed altogether.

See https://github.com/Intersmash/intersmash/pull/180#discussion_r1743137841

* Environment: `core` module
* Steps to reproduce: N/A

**Comment by TheMarvelFan** [comment]
Hi,
Is anyone working on this issue?

**Comment by TheMarvelFan** [comment]
Yes I'd love to work on it.

**Comment by fabiobrz** [comment]
> Yes I'd love to work on it.

Thanks! I've ssigned the issue to you, then :slightly_smiling_face:

**Comment by TheMarvelFan** [comment]
Hi @fabiobrz,

I've made the necessary changes and opened a PR. Please review it and let me know if any changes are rerquired.

Thanks!

**Comment by fabiobrz** [comment]
Closing as done via #203
