### ISSUE TITLE
Add getter for wildfly-eap8.keycloak-saml-adapter-galleon-pack.version

### ISSUE THREAD

**Issue by tommaso-borgato** [Intersmash/intersmash#27]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the solution you'd like**
Add a getter `IntersmashConfig.getKeycloakSamlAdapterGalleonPackVersion()` for property `wildfly-eap8.keycloak-saml-adapter-galleon-pack.version` 

**Describe alternatives you've considered**
Perhaps `wildfly-eap8.keycloak-saml-adapter-galleon-pack.version` might  have a better naming.

**Additional context**
`wildfly-eap8.keycloak-saml-adapter-galleon-pack.version`  is for the SAML adapter that can be added via feature pack:

```
<feature-pack>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-saml-adapter-galleon-pack</artifactId>
    <version>${keycloak-saml-adapter-galleon-pack.version}</version>
</feature-pack>
```

**Comment by fabiobrz** [comment]
This should be added to the WIldFly or Keycloak specific properties, see https://github.com/Intersmash/intersmash/blob/main/testsuite/deployments/deployments-provider/src/main/java/org/jboss/intersmash/test/deployments/WildflyDeploymentApplicationConfiguration.java
