### ISSUE TITLE
Create a custom Artemis Operator image to be used temporarily and to enable `ActiveMQOperatorProvisionerTest`

### ISSUE THREAD

**Issue by fabiobrz** [Intersmash/intersmash#32]
The `ActiveMQOperatorProvisionerTest`test class cannot be enabled because a catalog index image is not yet available anywhere for the Artemis Operator. There will be probably one available at some point during the next months, but the Artemis team suggest that we rely on a custom one in the meantime, which we'll build from scratch by following https://github.com/rh-messaging/activemq-artemis-operator/blob/main/docs/help/bundle.md#building

Once this is available, we'll set the required configuration in `global-properties` for Intersmash to let the `ActiveMQOperatorProvisioner` work properly,, by using a custom catalog source - similarly to what the `WildFlyOperatorProvisioner` is currently configured to do.

---
* Environment: testsuite module
* Steps to reproduce: `mvn clean install -DskipTests ; mvn test -pl testsuite/ -Dtest=ActiveMQOperatorProvisionerTest  -am -Dmaven.surefire.debug="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=localhost:8000"`

**Comment by tommaso-borgato** [comment]
fixed in https://github.com/Intersmash/intersmash/pull/45

**Comment by fabiobrz** [comment]
Thanks for your work on this issue @tommaso-borgato.

Closed as resolved via #45

**Comment by tommaso-borgato** [comment]
Posted procedure as https://source.redhat.com/personal_blogs/create_a_custom_artemis_operator_image_bundle_image_and_catalogindex_image

**Comment by fabiobrz** [comment]
> ~Posted procedure as ...~

Hi @tommaso-borgato - had to hide the comment since it contains an internal link. Feel free to correct me if I am wrong.
