### ISSUE TITLE
OpenShift template based provisioning support should be deprecated and tests removed 

### ISSUE THREAD

**Issue by fabiobrz** [Intersmash/intersmash#54]
Intersmash provides tooling for provisioning on OpenShift via templates, see https://github.com/Intersmash/intersmash/tree/main/tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/template

That being said, though, templates are being deprecated and disappeared already from some projects deliverables (e.g.: Infinispan, Keycloak) , being replaced by Operators or Helm Charts. Therefore the existing services template provisioning based implementation - see the Keykcloak template based provisioner [here](https://github.com/Intersmash/intersmash/blob/main/tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/template/KeycloakTemplateProvisioner.java) - should be removed from the sources.

Additionally, the testsuite contains some integration tests that validate the provisioning tooling for some projects, e.g.: [KeycloakTemplateTestCase](https://github.com/Intersmash/intersmash/blob/main/testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/KeycloakTemplateTestCase.java) which should be removed as well.

Specific corner cases - e.g.: some internal custom scenario using Red Hat SSO templates - will be evaluated in the future, when enabling support for the products like JBoss EAP, Red Hat SSO, Red Hat Data Grid and so on, in order to decide whether there is the need to resume one of the removed implementations.

In case no reasons will be found to do that, then the generic template provisioning based tooling - like the template based provisioner [interface](https://github.com/Intersmash/intersmash/blob/main/tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/provision/openshift/template/OpenShiftTemplateProvisioner.java#L34) for instance - should be deprecated for future removal.   

---
* Environment: testsuite
* Steps to reproduce: N/A

**Comment by tommaso-borgato** [comment]
@fabiobrz I have my OKR which might/might not use one of these: can we leave them around just the time I need to define the scenarios I have to implement?
